-- Product Iteration 21: store source-backed evidence before creating signals.

create table if not exists public.evidence (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  contact_id bigint references public.contacts(id) on delete set null,
  research_job_id bigint references public.research_jobs(id) on delete set null,
  evidence_type text not null check (btrim(evidence_type) <> ''),
  headline text not null,
  summary text not null,
  source_name text not null,
  source_url text not null,
  published_at timestamptz,
  discovered_at timestamptz not null default now(),
  confidence text not null check (confidence in ('High', 'Medium', 'Low')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists evidence_company_id_idx
  on public.evidence(company_id);

create index if not exists evidence_contact_id_idx
  on public.evidence(contact_id);

create index if not exists evidence_research_job_id_idx
  on public.evidence(research_job_id);

create index if not exists evidence_published_at_idx
  on public.evidence(published_at);

create index if not exists evidence_source_url_idx
  on public.evidence(source_url);

create unique index if not exists evidence_unique_source_event_idx
  on public.evidence(company_id, coalesce(contact_id, 0), source_url, headline);

alter table public.evidence enable row level security;

drop policy if exists "Allow prototype read access to evidence"
  on public.evidence;

create policy "Allow prototype read access to evidence"
  on public.evidence
  for select
  to anon
  using (true);

drop policy if exists "Allow prototype insert access to evidence"
  on public.evidence;

create policy "Allow prototype insert access to evidence"
  on public.evidence
  for insert
  to anon
  with check (
    company_id is not null
    and btrim(evidence_type) <> ''
    and btrim(headline) <> ''
    and btrim(summary) <> ''
    and btrim(source_name) <> ''
    and btrim(source_url) <> ''
    and confidence in ('High', 'Medium', 'Low')
  );
