-- Product Iteration 17: record CSV contact import runs.

create table if not exists public.import_runs (
  id bigint generated by default as identity primary key,
  file_name text not null,
  total_rows integer not null,
  valid_rows integer not null,
  invalid_rows integer not null,
  imported_companies integer not null,
  imported_contacts integer not null,
  created_at timestamptz not null default now()
);

alter table public.import_runs enable row level security;

drop policy if exists "Allow prototype read access to import runs" on public.import_runs;
create policy "Allow prototype read access to import runs"
  on public.import_runs
  for select
  to anon
  using (true);

drop policy if exists "Allow prototype insert access to import runs" on public.import_runs;
create policy "Allow prototype insert access to import runs"
  on public.import_runs
  for insert
  to anon
  with check (true);
