-- Product Iteration 19: queue company research work without external providers.

create table if not exists public.research_jobs (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  status text not null default 'Waiting'
    check (status in ('Waiting', 'Researching', 'Complete', 'Failed')),
  started_at timestamptz,
  completed_at timestamptz,
  provider text,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists research_jobs_company_id_idx
  on public.research_jobs(company_id);

create index if not exists research_jobs_status_idx
  on public.research_jobs(status);

create unique index if not exists research_jobs_one_active_job_per_company_idx
  on public.research_jobs(company_id)
  where status in ('Waiting', 'Researching');

alter table public.research_jobs enable row level security;

drop policy if exists "Allow prototype read access to research jobs"
  on public.research_jobs;

create policy "Allow prototype read access to research jobs"
  on public.research_jobs
  for select
  to anon
  using (true);

drop policy if exists "Allow prototype insert access to research jobs"
  on public.research_jobs;

create policy "Allow prototype insert access to research jobs"
  on public.research_jobs
  for insert
  to anon
  with check (
    status = 'Waiting'
    and started_at is null
    and completed_at is null
    and provider is null
    and error_message is null
  );
