-- Sprint 13: persist call outcomes for worked prospects.
-- Run this in Supabase SQL Editor after confirming the existing contacts/signals ids are bigint.

create table if not exists public.call_outcomes (
  id bigint generated by default as identity primary key,
  contact_id bigint not null references public.contacts(id) on delete cascade,
  signal_id bigint references public.signals(id) on delete set null,
  disposition text not null,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists call_outcomes_contact_id_created_at_idx
  on public.call_outcomes (contact_id, created_at desc);

alter table public.call_outcomes enable row level security;

drop policy if exists "Allow prototype read access to call outcomes" on public.call_outcomes;
create policy "Allow prototype read access to call outcomes"
  on public.call_outcomes
  for select
  to anon
  using (true);

drop policy if exists "Allow prototype insert access to call outcomes" on public.call_outcomes;
create policy "Allow prototype insert access to call outcomes"
  on public.call_outcomes
  for insert
  to anon
  with check (true);
