-- Product Iteration 22: track provider-level results for each company research job.

create table if not exists public.research_provider_runs (
  id bigint generated by default as identity primary key,
  research_job_id bigint not null references public.research_jobs(id) on delete cascade,
  provider_id text not null,
  provider_name text not null,
  status text not null check (status in ('Completed', 'No Evidence', 'Failed', 'Skipped')),
  evidence_count integer not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  error_message text,
  created_at timestamptz not null default now()
);

create unique index if not exists research_provider_runs_job_provider_idx
  on public.research_provider_runs(research_job_id, provider_id);

create index if not exists research_provider_runs_research_job_id_idx
  on public.research_provider_runs(research_job_id);

create index if not exists research_provider_runs_status_idx
  on public.research_provider_runs(status);

alter table public.research_provider_runs enable row level security;

drop policy if exists "Allow prototype read access to research provider runs"
  on public.research_provider_runs;

create policy "Allow prototype read access to research provider runs"
  on public.research_provider_runs
  for select
  to anon
  using (true);

drop policy if exists "Allow prototype insert access to research provider runs"
  on public.research_provider_runs;

create policy "Allow prototype insert access to research provider runs"
  on public.research_provider_runs
  for insert
  to anon
  with check (
    btrim(provider_id) <> ''
    and btrim(provider_name) <> ''
    and status in ('Completed', 'No Evidence', 'Failed', 'Skipped')
    and evidence_count >= 0
  );

drop policy if exists "Allow prototype update access to research provider runs"
  on public.research_provider_runs;

create policy "Allow prototype update access to research provider runs"
  on public.research_provider_runs
  for update
  to anon
  using (true)
  with check (
    btrim(provider_id) <> ''
    and btrim(provider_name) <> ''
    and status in ('Completed', 'No Evidence', 'Failed', 'Skipped')
    and evidence_count >= 0
  );

drop policy if exists "Allow prototype status updates to research jobs"
  on public.research_jobs;

create policy "Allow prototype status updates to research jobs"
  on public.research_jobs
  for update
  to anon
  using (true)
  with check (
    status in ('Waiting', 'Researching', 'Complete', 'Failed')
  );
