-- Product Iteration 36: capture lightweight mission outcomes for recommendation feedback.

create table if not exists public.mission_outcomes (
  id bigint generated by default as identity primary key,
  mission_id text not null,
  company_id bigint not null references public.companies(id),
  contact_id bigint references public.contacts(id),
  business_profile_id bigint references public.business_profiles(id),
  occurred_at timestamptz not null default now(),
  connected boolean not null,
  outcome text not null
    check (
      outcome in (
        'Voicemail',
        'No Answer',
        'Wrong Person',
        'Meeting Booked',
        'Follow Up',
        'Timing',
        'No Budget',
        'Already Customer',
        'Not Interested',
        'Disqualified'
      )
    ),
  follow_up_date timestamptz,
  recommended_next_action text,
  reason text,
  learned_signal text,
  notes text,
  client_submission_id text not null,
  created_at timestamptz not null default now(),
  check (length(trim(mission_id)) > 0),
  check (length(trim(client_submission_id)) > 0),
  check (length(trim(outcome)) > 0),
  check (
    (connected = false and outcome in ('Voicemail', 'No Answer'))
    or
    (connected = true and outcome not in ('Voicemail', 'No Answer'))
  ),
  check (follow_up_date is null or outcome in ('Follow Up', 'Timing')),
  check (reason is null or length(trim(reason)) <= 80),
  check (learned_signal is null or length(trim(learned_signal)) <= 120),
  check (notes is null or length(trim(notes)) <= 200)
);

create index if not exists mission_outcomes_mission_id_idx
  on public.mission_outcomes(mission_id);

create index if not exists mission_outcomes_company_id_idx
  on public.mission_outcomes(company_id);

create index if not exists mission_outcomes_contact_id_idx
  on public.mission_outcomes(contact_id);

create index if not exists mission_outcomes_business_profile_id_idx
  on public.mission_outcomes(business_profile_id);

create index if not exists mission_outcomes_occurred_at_idx
  on public.mission_outcomes(occurred_at);

create index if not exists mission_outcomes_follow_up_date_idx
  on public.mission_outcomes(follow_up_date)
  where follow_up_date is not null;

create unique index if not exists mission_outcomes_client_submission_id_idx
  on public.mission_outcomes(client_submission_id);

alter table public.mission_outcomes enable row level security;

drop policy if exists "Allow prototype read access to mission outcomes"
  on public.mission_outcomes;

create policy "Allow prototype read access to mission outcomes"
  on public.mission_outcomes
  for select
  to anon
  using (true);
