-- Product Iteration 31: store the SDR business profile that guides future discovery.

create table if not exists public.business_profiles (
  id bigint generated by default as identity primary key,
  profile_name text not null default 'Default Profile',
  company_name text not null,
  product_name text not null,
  product_description text not null,
  value_propositions jsonb not null default '[]'::jsonb,
  customer_problems jsonb not null default '[]'::jsonb,
  target_industries jsonb not null default '[]'::jsonb,
  target_sub_industries jsonb not null default '[]'::jsonb,
  employee_min integer,
  employee_max integer,
  revenue_min bigint,
  revenue_max bigint,
  target_geographies jsonb not null default '[]'::jsonb,
  ownership_preferences jsonb not null default '[]'::jsonb,
  excluded_industries jsonb not null default '[]'::jsonb,
  excluded_company_types jsonb not null default '[]'::jsonb,
  priority_titles jsonb not null default '[]'::jsonb,
  secondary_titles jsonb not null default '[]'::jsonb,
  relevant_departments jsonb not null default '[]'::jsonb,
  management_levels jsonb not null default '[]'::jsonb,
  excluded_titles jsonb not null default '[]'::jsonb,
  high_priority_signals jsonb not null default '[]'::jsonb,
  medium_priority_signals jsonb not null default '[]'::jsonb,
  low_priority_signals jsonb not null default '[]'::jsonb,
  ignored_signals jsonb not null default '[]'::jsonb,
  signal_recency_days integer,
  call_objective text,
  meeting_outcome text,
  common_objections jsonb not null default '[]'::jsonb,
  approved_themes jsonb not null default '[]'::jsonb,
  territory_rules jsonb not null default '{}'::jsonb,
  source_restrictions jsonb not null default '[]'::jsonb,
  historical_success_notes text,
  profile_version integer not null default 1,
  last_user_confirmed_at timestamptz,
  learning_enabled boolean not null default false,
  minimum_outcomes_before_recommendations integer not null default 25,
  learned_recommendations jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (employee_min is null or employee_min >= 0),
  check (employee_max is null or employee_max >= 0),
  check (employee_min is null or employee_max is null or employee_min <= employee_max),
  check (revenue_min is null or revenue_min >= 0),
  check (revenue_max is null or revenue_max >= 0),
  check (revenue_min is null or revenue_max is null or revenue_min <= revenue_max),
  check (signal_recency_days is null or signal_recency_days > 0),
  check (profile_version > 0),
  check (minimum_outcomes_before_recommendations > 0)
);

create index if not exists business_profiles_is_active_idx
  on public.business_profiles(is_active);

create index if not exists business_profiles_created_at_idx
  on public.business_profiles(created_at);

create unique index if not exists business_profiles_one_active_profile_idx
  on public.business_profiles(is_active)
  where is_active = true;

create or replace function public.set_business_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_business_profiles_updated_at
  on public.business_profiles;

create trigger set_business_profiles_updated_at
  before update on public.business_profiles
  for each row
  execute function public.set_business_profiles_updated_at();

alter table public.business_profiles enable row level security;

drop policy if exists "Allow prototype read access to business profiles"
  on public.business_profiles;

create policy "Allow prototype read access to business profiles"
  on public.business_profiles
  for select
  to anon
  using (true);

drop policy if exists "Allow prototype insert access to business profiles"
  on public.business_profiles;

create policy "Allow prototype insert access to business profiles"
  on public.business_profiles
  for insert
  to anon
  with check (
    length(trim(company_name)) > 0
    and length(trim(product_name)) > 0
    and length(trim(product_description)) > 0
    and profile_version > 0
    and minimum_outcomes_before_recommendations > 0
    and jsonb_typeof(value_propositions) = 'array'
    and jsonb_typeof(customer_problems) = 'array'
    and jsonb_typeof(target_industries) = 'array'
    and jsonb_typeof(target_sub_industries) = 'array'
    and jsonb_typeof(target_geographies) = 'array'
    and jsonb_typeof(ownership_preferences) = 'array'
    and jsonb_typeof(excluded_industries) = 'array'
    and jsonb_typeof(excluded_company_types) = 'array'
    and jsonb_typeof(priority_titles) = 'array'
    and jsonb_typeof(secondary_titles) = 'array'
    and jsonb_typeof(relevant_departments) = 'array'
    and jsonb_typeof(management_levels) = 'array'
    and jsonb_typeof(excluded_titles) = 'array'
    and jsonb_typeof(high_priority_signals) = 'array'
    and jsonb_typeof(medium_priority_signals) = 'array'
    and jsonb_typeof(low_priority_signals) = 'array'
    and jsonb_typeof(ignored_signals) = 'array'
    and jsonb_typeof(common_objections) = 'array'
    and jsonb_typeof(approved_themes) = 'array'
    and jsonb_typeof(territory_rules) = 'object'
    and jsonb_typeof(source_restrictions) = 'array'
    and jsonb_typeof(learned_recommendations) = 'object'
  );

drop policy if exists "Allow prototype update access to business profiles"
  on public.business_profiles;

create policy "Allow prototype update access to business profiles"
  on public.business_profiles
  for update
  to anon
  using (true)
  with check (
    length(trim(company_name)) > 0
    and length(trim(product_name)) > 0
    and length(trim(product_description)) > 0
    and profile_version > 0
    and minimum_outcomes_before_recommendations > 0
    and jsonb_typeof(value_propositions) = 'array'
    and jsonb_typeof(customer_problems) = 'array'
    and jsonb_typeof(target_industries) = 'array'
    and jsonb_typeof(target_sub_industries) = 'array'
    and jsonb_typeof(target_geographies) = 'array'
    and jsonb_typeof(ownership_preferences) = 'array'
    and jsonb_typeof(excluded_industries) = 'array'
    and jsonb_typeof(excluded_company_types) = 'array'
    and jsonb_typeof(priority_titles) = 'array'
    and jsonb_typeof(secondary_titles) = 'array'
    and jsonb_typeof(relevant_departments) = 'array'
    and jsonb_typeof(management_levels) = 'array'
    and jsonb_typeof(excluded_titles) = 'array'
    and jsonb_typeof(high_priority_signals) = 'array'
    and jsonb_typeof(medium_priority_signals) = 'array'
    and jsonb_typeof(low_priority_signals) = 'array'
    and jsonb_typeof(ignored_signals) = 'array'
    and jsonb_typeof(common_objections) = 'array'
    and jsonb_typeof(approved_themes) = 'array'
    and jsonb_typeof(territory_rules) = 'object'
    and jsonb_typeof(source_restrictions) = 'array'
    and jsonb_typeof(learned_recommendations) = 'object'
  );
